// <auto-generated />
namespace ShoppingCart2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _100ta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_100ta));
        
        string IMigrationMetadata.Id
        {
            get { return "201806130954401_100ta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
